# Generated by Django 4.2.3 on 2023-07-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('mediaType', models.CharField(choices=[('Telegram', 'Telegram'), ('Whatsapp', 'Whatsapp')], max_length=10)),
            ],
        ),
    ]
