# Generated by Django 4.2.3 on 2023-07-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendMessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='chatID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='batch',
            name='errorCode',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='batch',
            name='errorDescription',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='batch',
            name='groupName',
            field=models.CharField(default='Automated school notifier', max_length=100),
        ),
        migrations.AddField(
            model_name='batch',
            name='messageID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='statusCode',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='batch',
            name='mediaType',
            field=models.CharField(choices=[('Telegram', 'Telegram'), ('Whatsapp', 'Whatsapp')], default='Telegram', max_length=10),
        ),
    ]
