# Generated by Django 4.2.3 on 2023-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendMessage', '0002_batch_chatid_batch_errorcode_batch_errordescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='errorCode',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='errorDescription',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
