# Generated by Django 4.2.3 on 2023-07-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendMessage', '0005_alter_batch_chatid_alter_batch_messageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='groupName',
            field=models.CharField(default='Automated school notifier', max_length=100, null=True),
        ),
    ]
