# Generated by Django 4.2.3 on 2023-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendMessage', '0006_alter_batch_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='mediaType',
            field=models.CharField(choices=[('Telegram', 'Telegram'), ('MAil', 'Mail')], default='Telegram', max_length=10),
        ),
    ]
